### PR TITLE
CAP-7--Create-New-Account-Page

### PR DESCRIPTION
**Pull request by mgckq8**

### CODE REVIEW

**Comment by mgckq8** [comment]
register
register-badPass
register-badEmail

Screenshots with some example errors. Other errors will be thrown if the user leaves a textbox empty.

**Comment by RajuNichols** [comment]
Register
Here is how it looks on Android

**Comment by mgckq8** [comment]
Screenshot 2023-01-28 at 4 44 00 PM
With the changes made for Android. Need to look into having separate styling for iOS and Android.

**Comment by mgckq8** [comment]
fixed-ios
updated iOS styling

**Review by RajuNichols — APPROVED** [review]
Looks good

**Pull request merged**
