### PR TITLE
CAP-6 Landing Page

### PR DESCRIPTION
**Pull request by RajuNichols**
- Fonts
-  Loading
- ReactNativePaper
- Title
- Text inputs
- Register Button/Text

CAP-6

### CODE REVIEW

**Comment by RajuNichols** [comment]
SS
current landing in progress

**Comment by RajuNichols** [comment]
SS
Current Progress

**Review by mgckq8 — APPROVED** [review]
Nice.

**Comment by mgckq8** [comment]
iphone

**Review by mgckq8 — APPROVED** [review]
Tested on iOS simulator and everything looks good.

**Pull request merged**
