### PR TITLE
Cap 8  create questionnaire page

### PR DESCRIPTION
**Pull request by mgckq8**
Screenshot 2023-02-27 at 10 47 53 PM
Screenshot 2023-02-27 at 10 48 01 PM
Screenshot 2023-02-27 at 10 48 41 PM
The page loads with the options automatically unselected and will display an error if the user hits the submit button without answering all of the questions.

### CODE REVIEW

**Comment by mgckq8** [comment]
Also the way I applied the color scheme doesn't look the greatest but it looks better than the old one for sure.

**Comment by RajuNichols** [comment]
I can't run on Android. I did a yarn install and then tried to restart expo and I get an error. It's about the package you installed. did you use yarn to install the package? The reason I think that is because if you installed a new package there would be a change in the yarn.lock file to include it as a dependency but I don't see a change for that.

**Comment by RajuNichols** [comment]
questionaire
I was able to fix the issue for the app loading. I will note that there are some parameters that the file says are wrong but ignore them.

**Review by RajuNichols — APPROVED** [review]
Looked good to me

**Comment by RajuNichols** [comment]
I'd make sure it still doesnt break for you before you merge this branch in

**Comment by mgckq8** [comment]
Seems to be working fine 👍

**Pull request merged**
