### PR TITLE
CAP-10 Challenge Desc Page

### PR DESCRIPTION
**Pull request by RajuNichols**
Added Majority of Screen

### CODE REVIEW

**Comment by RajuNichols** [comment]
SS

**Comment by mgckq8** [comment]
Screenshot 2023-02-07 at 3 21 16 PM
Here's what it looks like on iOS right now. I will adjust that in a bit.

**Comment by mgckq8** [comment]
The link works fine.

**Comment by mgckq8** [comment]
Probably good to add these to App.jsx so that it doesn't have to be done later, but not a big deal because it's not routed to anything yet anyways.

import ChallengeDescriptionPage from "./screens/ChallengeDescriptionPage";
<Stack.Screen name="ChallengeDescriptionPage" component={ChallengeDescriptionPage} />

**Comment by mgckq8** [comment]
Screenshot 2023-02-07 at 3 44 50 PM
iOS with fixed spacing.

**Comment by mgckq8** [comment]
Only other thing I'd suggest is maybe make the about portion have a scrollbar.

**Review by mgckq8 — APPROVED** [review]
sick

**Pull request merged**
